# ==============================================================================
# kkhypr: hyprpaper configuration
# ==============================================================================

preload = /usr/share/hypr/wall0.png
wallpaper = , /usr/share/hypr/wall0.png
splash = false
ipc = on
