monitor.bluez.properties = {
  bluez5.roles = [ a2dp_sink a2dp_source hfp_hf hfp_ag ]
  bluez5.codecs = [ ldac aac aptx_hd aptx sbc_xq sbc ]
  bluez5.enable-sbc-xq = true
  bluez5.enable-msbc = true
  bluez5.enable-hw-volume = true
}

wireplumber.settings = {
  bluetooth.autoswitch-to-headset-profile = false
  linking.follow-default-target = true
  device.routes.mute-on-bluetooth-playback-removed = false
  device.routes.default-sink-volume = 0.40
}
